-- App-specific tweaks
require("hyprland.apps.browser")
require("hyprland.apps.pip")
require("hyprland.apps.qemu")
require("hyprland.apps.rtl")
require("hyprland.apps.steam")
require("hyprland.apps.terminals")
require("hyprland.apps.dolphin")
require("hyprland.apps.zenity")
require("hyprland.apps.vpn")
require("hyprland.apps.chatterino")
require("hyprland.apps.games")
require("hyprland.apps.mpv")
require("hyprland.apps.discord")
require("hyprland.apps.teamspeak")
require("hyprland.apps.spotify")
require("hyprland.apps.tkinter")
require("hyprland.apps.thunar")
