-- MONITOR CONFIG
-- Declared in monitors.lua, matched on EDID description rather than connector
-- name so the config is not bound to this machine's ports.
require("hyprland.monitors")

hl.config({ render = { expand_undersized_textures = false } })

-- Variables
-- Colors come from the active look (generated by `look`, see dotfiles/config/look).
-- The fallback keeps the session usable before the first `look apply`.
local ok, look = pcall(require, "hyprland.look")
if not ok then
	look = {
		border_active = { colors = { "rgba(589ED7ee)", "rgba(0DB9D7ee)" }, angle = 45 },
		border_inactive = "rgba(595959aa)",
		bar = "rgba(161A2Dcc)",
		text = "rgba(ffffffff)",
		text_dim = "rgba(ffffff90)",
	}
end
local activeBorderColor = look.border_active
local inactiveBorderColor = look.border_inactive

hl.config({
	input = {
		kb_layout = "us",
		kb_options = "caps:escape",
		numlock_by_default = true,
		repeat_delay = 250,
		repeat_rate = 35,
		accel_profile = "flat",
		sensitivity = -0.5,

		touchpad = {
			natural_scroll = true,
			disable_while_typing = true,
			clickfinger_behavior = true,
			scroll_factor = 0.5,
		},
		follow_mouse = 1,
	},

	binds = {
		scroll_event_delay = 0,
	},
	gestures = {
		workspace_swipe_distance = 700,
		workspace_swipe_cancel_ratio = 0.2,
		workspace_swipe_min_speed_to_force = 5,
		workspace_swipe_direction_lock = true,
		workspace_swipe_direction_lock_threshold = 10,
		workspace_swipe_create_new = true,
	},
	dwindle = {
		preserve_split = true,
		force_split = 2,
		smart_split = false,
		smart_resizing = false,
	},
	general = {
		gaps_in = 4,
		gaps_out = {
			top = 3,
			right = 2,
			bottom = 2,
			left = 2,
		},

		border_size = 0,

		resize_on_border = true,

		allow_tearing = false,

		layout = "dwindle",
		col = {
			active_border = activeBorderColor,
			inactive_border = inactiveBorderColor,
		},
	},
	decoration = {
		rounding = 8,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
		},

		blur = {
			enabled = true,
			size = 12,
			passes = 3,
			vibrancy = 0.2,
			-- menus and other popups blur too, so translucent menus stay readable
			popups = true,
			popups_ignorealpha = 0.2,
		},
	},
	-- Hyprbars is enabled through hyprpm. Keep its chrome intentionally quiet:
	-- it is only visible on floating windows (see rules.lua), borrowing the
	-- Waybar/Tokyo Night surface, the notification text colour, and our cyan
	-- accent through the existing window border.
	plugin = {
		hyprbars = {
			enabled = true,
			bar_color = look.bar,
			bar_height = 18,
			bar_blur = true,
			bar_title_enabled = false,
			col = {
				text = "rgb(cdd6f4)",
			},
		},
	},
	group = {
		col = {
			border_active = activeBorderColor,
			border_inactive = inactiveBorderColor,
		},

		groupbar = {
			col = {
				active = "rgba(00000040)",
				inactive = "rgba(00000020)",
			},
			font_size = 12,
			font_family = "monospace",
			font_weight_active = "ultraheavy",
			font_weight_inactive = "normal",
			text_color = look.text,
			text_color_inactive = look.text_dim,

			indicator_height = 0,
			indicator_gap = 5,
			height = 22,
			gaps_in = 5,
			gaps_out = 0,

			gradients = true,
			gradient_rounding = 0,
			gradient_round_only_edges = false,
		},
	},
	animations = {
		enabled = true,
	},
	misc = {
		disable_splash_rendering = true,
		focus_on_activate = false,
		anr_missed_pings = 3,
		-- vrr is set per-monitor in monitors.lua. Adaptive sync support is a
		-- property of the panel, and forcing it globally means a display that
		-- flickers under VRR drags the others along with it.
		animate_manual_resizes = false,
		animate_mouse_windowdragging = false,
		enable_swallow = false,
		swallow_regex = "(foot | kitty | allacritty | Alacritty | ghostty | Ghostty | com.raggesilver.BlackBox)",

		disable_hyprland_logo = true,
		force_default_wallpaper = 0,

		allow_session_lock_restore = true,

		initial_workspace_tracking = 0,
	},
	cursor = {
		hide_on_key_press = true,
	},
	xwayland = {
		-- Keeps XWayland clients from being rendered at the wrong scale and
		-- upscaled into blur. Harmless at scale 1; matters as soon as a
		-- higher-DPI display is attached.
		force_zero_scaling = true,
	},
	ecosystem = {
		no_update_news = true,
		no_donation_nag = true,
	},
})

hl.curve("easeOut", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "easeOut" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.5, bezier = "easeOut" })
hl.animation({ leaf = "border", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1, bezier = "default", style = "slidefade" })
