$width = 443
$height = 250
$gap = 20
$dolphin_progress = match:initial_title ^(.*)(Copying|Moving)(.*)$, match:class org.kde.dolphin

windowrule = float on, $dolphin_progress
windowrule = center on, $dolphin_progress
windowrule = pin on, $dolphin_progress

windowrule = move (monitor_w-$width-$gap) (monitor_h-$height-$gap), $dolphin_progress
