#!/usr/bin/env bash
# Generates the machine-specific half of the uwsm environment.
#
# ~/.config/uwsm/env is tracked and vendor-neutral: toolkits, input methods,
# session identity. Everything there is true on any machine.
#
# ~/.config/uwsm/env-hyprland is generated here and NOT tracked, because every
# variable in it is a property of the hardware:
#   - AQ_DRM_DEVICES depends on DRM card numbering, which is probe order
#   - the NVIDIA variables are wrong (and harmful) on an AMD machine
#   - the shader cache variable has a different name per GPU vendor
#
# uwsm sources env first, then env-<compositor>, so this file wins where they
# overlap. Regenerate by re-running this script; it is safe to run repeatedly.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/lib/facts.sh"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'
print_msg() { echo -e "${GREEN}[*] $1${NC}"; }
print_skip() { echo -e "${BLUE}[=] $1${NC}"; }

DEST="$HOME/.config/uwsm/env-hyprland"
mkdir -p "$(dirname "$DEST")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by install/core/env.sh on $(date -I). Do not edit."
  echo "# Machine: $FACT_HOSTNAME  GPU: $FACT_GPU_VENDORS  Cards: $FACT_GPU_CARDS"
  echo

  # --- DRM device order ---------------------------------------------------
  # Only meaningful with more than one GPU. Integrated first so the compositor
  # renders on it and the discrete card stays available for offload; listing
  # the dGPU first on a laptop costs battery for no gain.
  if [ "$FACT_GPU_COUNT" -gt 1 ]; then
    integrated=""
    discrete=""
    for pair in $FACT_GPU_CARDS; do
      card="${pair%%:*}"
      vendor="${pair##*:}"
      if [ "$vendor" = "nvidia" ]; then
        discrete="${discrete:+$discrete:}/dev/dri/$card"
      else
        integrated="${integrated:+$integrated:}/dev/dri/$card"
      fi
    done
    order="${integrated:+$integrated}${integrated:+${discrete:+:}}${discrete:-}"
    echo "# Hybrid graphics: integrated first, discrete available for offload"
    echo "export AQ_DRM_DEVICES=\"$order\""
    echo
  fi

  # --- vendor-specific ------------------------------------------------------
  case "$FACT_GPU_VENDORS" in
  *nvidia*)
    echo "# NVIDIA"
    echo "export LIBVA_DRIVER_NAME=nvidia"
    echo "export __GLX_VENDOR_LIBRARY_NAME=nvidia"
    echo "export GBM_BACKEND=nvidia-drm"
    echo "export NVD_BACKEND=direct"
    # Gates VRR on NVIDIA; without it adaptive sync stays off regardless of
    # what the monitor and compositor negotiate.
    echo "export __GL_GSYNC_ALLOWED=1"
    # Raise the shader cache ceiling so large games stop recompiling every
    # launch. Vendor-specific: the Mesa variable does nothing here.
    echo "export __GL_SHADER_DISK_CACHE_SIZE=12000000000"
    if [ "$FACT_GPU_COUNT" -gt 1 ]; then
      echo "export __VK_LAYER_NV_optimus=NVIDIA_only"
    fi
    echo
    ;;
  esac

  case "$FACT_GPU_VENDORS" in
  *amd* | *intel*)
    echo "# Mesa (AMD / Intel)"
    echo "export MESA_SHADER_CACHE_MAX_SIZE=12G"
    echo
    ;;
  esac
} >"$tmp"

if [ -f "$DEST" ] && diff -q <(tail -n +2 "$tmp") <(tail -n +2 "$DEST") >/dev/null 2>&1; then
  # Compare past the date line so an unchanged machine does not churn the file.
  print_skip "uwsm env-hyprland: already current"
else
  print_msg "writing $DEST"
  install -Dm644 "$tmp" "$DEST"
  sed 's/^/    /' "$DEST"
fi
