#!/usr/bin/env bash
# Set up TeamSpeak 3 so `look` can tint its DarkenTS style.
#
# DarkenTS is licensed no-sharing/no-derivatives, so this repo never holds any of it. This
# script only works on the user's own copy: it installs the style from a .ts3_style file
# if one is given (or sits in ~/Downloads), keeps an untouched copy of the style files
# where `look` reads them, and renders the tint. Nothing is changed if DarkenTS is absent.
#
# Usage: teamspeak.sh [path/to/DarkenTS*.ts3_style]
set -euo pipefail

STYLES="$HOME/.ts3client/styles"
PRISTINE="${XDG_DATA_HOME:-$HOME/.local/share}/look/darkents"
MARK='Generated by `look`'
FILES=(DarkenTS.qss DarkenTS_chat.qss)

if pgrep -x ts3client_linux >/dev/null || pgrep -f 'ts3client_linux' >/dev/null; then
  echo "TeamSpeak is running; the style is read at start, so restart it afterwards." >&2
fi

pkg="${1:-}"
if [ -z "$pkg" ]; then
  pkg="$(find "$HOME/Downloads" -maxdepth 1 -name 'DarkenTS*.ts3_style' 2>/dev/null | head -n 1)"
fi

if [ ! -f "$STYLES/DarkenTS.qss" ] && [ -n "$pkg" ]; then
  mkdir -p "$STYLES"
  # The archive carries its own styles/ folder, so it unpacks over the TeamSpeak root.
  unzip -oq "$pkg" -x package.ini -d "$HOME/.ts3client"
  echo "teamspeak: installed DarkenTS from $pkg"
fi
if [ ! -f "$STYLES/DarkenTS.qss" ]; then
  echo "teamspeak: DarkenTS is not installed; download it (TeamSpeak add-ons) and run this again with its .ts3_style file." >&2
  exit 0
fi

# Keep the original of each file, taken only while the file is still the untouched one.
mkdir -p "$PRISTINE"
for f in "${FILES[@]}"; do
  if [ -f "$STYLES/$f" ] && ! head -n 1 "$STYLES/$f" | grep -qF "$MARK"; then
    cp "$STYLES/$f" "$PRISTINE/$f"
  fi
done

[ -x "$HOME/.local/bin/look" ] && "$HOME/.local/bin/look" --no-reload apply || true
