return {
	--	{
	--		"sudo-tee/opencode.nvim",
	--		opts = {
	--			keymap_prefix = "<Leader>a",
	--
	--			ui = {
	--				input = {
	--					text = { wrap = true },
	--				},
	--			},
	--		},
	--
	--		dependencies = {
	--			"nvim-lua/plenary.nvim",
	--			{
	--				"MeanderingProgrammer/render-markdown.nvim",
	--				opts = {
	--					anti_conceal = { enabled = false },
	--					file_types = { "markdown", "opencode_output" },
	--				},
	--				ft = { "markdown", "Avante", "copilot-chat", "opencode_output" },
	--			},
	--			"saghen/blink.cmp",
	--			"folke/snacks.nvim",
	--		},
	--	},
}
