-- Generated by `look`. Do not edit; change the look instead.
return {
	border_active = { colors = { "{{border_active|hl=ee}}", "{{border_active_alt|hl=ee}}" }, angle = 45 },
	border_inactive = "{{border_inactive|hl=aa}}",
	bar = "{{bar_bg|hl=cc}}",
	text = "{{fg|hl}}",
	text_dim = "{{fg|hl=90}}",
}
