foreground            {{fg}}
background            {{bg}}
selection_foreground  {{fg}}
selection_background  {{selection}}
cursor                {{cursor}}
cursor_text_color     {{bg}}
url_color             {{accent_alt}}
active_border_color   {{accent}}
inactive_border_color {{border}}
color0  {{t0}}
color1  {{t1}}
color2  {{t2}}
color3  {{t3}}
color4  {{t4}}
color5  {{t5}}
color6  {{t6}}
color7  {{t7}}
color8  {{t8}}
color9  {{t9}}
color10 {{t10}}
color11 {{t11}}
color12 {{t12}}
color13 {{t13}}
color14 {{t14}}
color15 {{t15}}
