-- Generated by `look`. Do not edit; change the look instead.
return {
  bg = "{{bg}}",
  bg_alt = "{{bg_alt}}",
  surface = "{{surface}}",
  border = "{{border}}",
  fg = "{{fg}}",
  fg_dim = "{{fg_dim}}",
  accent = "{{accent}}",
  accent_alt = "{{accent_alt}}",
  selection = "{{selection}}",
  ok = "{{ok}}",
  warn = "{{warn}}",
  danger = "{{danger}}",
}
